name = "GenFlux"
uuid = "bf80db26-2df5-4c23-a907-3a9ed30ce870"
authors = ["femtomc <mccoybecker@gmail.com>"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1"
Gen = "0.3.5"
Zygote = "0.5"
Flux = "0.11"
